"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 3.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
from os.path import join
from pyqiwip2p import QiwiP2P
from yoomoney import Client

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Application definition

INSTALLED_APPS = [
    'jet',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'django_filters',
    'ratelimit',
    'widget_tweaks',
    'ckeditor',
    'constance',
    'constance.backends.database',

    'shop.apps.ShopConfig',
    'user.apps.UserConfig',
]

MIDDLEWARE = [
    'core.middleware.ReverseProxy',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    'core.middleware.Maintetance',
    'core.middleware.CheckPayments',
    'ratelimit.middleware.RatelimitMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'constance.context_processors.config',
                'core.context_processors.footer_settings',
            ],
        },
    },
]

AUTHENTICATION_BACKENDS = [
    'user.auth.EmailBackend',
]

WSGI_APPLICATION = 'core.wsgi.application'


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'ru-ru'

TIME_ZONE = 'Europe/Moscow'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/source/'
STATIC_ROOT = join(BASE_DIR, 'source')
STATICFILES_DIRS = [
    join(BASE_DIR, 'core/source')
]

# Media files
MEDIA_ROOT = join(BASE_DIR, 'assets')
MEDIA_URL = '/assets/'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
DEFAULT_FILE_STORAGE = 'django_hashedfilenamestorage.storage.HashedFilenameFileSystemStorage'
RATELIMIT_VIEW = 'shop.views.ratelimited'

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.filebased.FileBasedCache',
        'LOCATION': join(BASE_DIR, 'cache'),
    }
}

# EMAIL SETTINGS
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.mail.ru'
EMAIL_PORT = 2525
EMAIL_USE_TLS = True

EMAIL_HOST_USER = "umail"
EMAIL_HOST_PASSWORD = "mailpassword"
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

LOGIN_REDIRECT_URL = '/'
LOGIN_URL = '/auth/'

AUTH_USER_MODEL = 'user.User'

SESSION_COOKIE_AGE = 60 * 60 * 24 * 7

# CONSTANCE
CONSTANCE_BACKEND = 'constance.backends.database.DatabaseBackend'

CONSTANCE_ADDITIONAL_FIELDS = {
    'image_field': ['django.forms.ImageField', {'required': False}]
}

CONSTANCE_CONFIG = {
    'SITE_NAME': ('Your Store', 'Укажите название вашего сайта.',),
    'LOGO_IMAGE': ('', 'Вставьте логотип сайта.', 'image_field'),
    'PANEL_TEXT': ('Всем привет! Наш магазин работает, оплата проходит, ограничений нет.',
                   'Это будет отображаться в панели на главной странице.'),
    'GIFTS': (True, 'При включении на сайте будет доступна возможность получить подарок.'),
    'CHECK_PAYMENTS_TIMEOUT': (150, 'Проверять всевозможные платежи через * секунд. Рекомендуется оставить как есть.'),
    'MAINTENANCE': (False,
                    'Технический перерыв. Внимание! При ВКЛЮЧЕНИИ всегда оставлять суперпользователей, в противном случае придётся создавать нового через консоль. Для суперпользователей тех. перерыв не работает.'),

    'USERS_COUNT': (-1, 'Введите количество пользователей.'),
    'TODAY_USERS_COUNT': (-1, 'Введите количество пользователей сегодня.',),
    'PURCHASES_COUNT': (-1, 'Введите количество покупок.',),

    'CONTACT1': ('', 'Введите первый контакт для связи.',),
    'CONTACT1_LABEL': ('', 'Введите название контакта (пример: Vk, Telegram).',),
    'CONTACT1_URL': ('', 'Вставьте ссылку на контакт.',),
    'CONTACT2': ('', 'Введите второй контакт для связи.',),
    'CONTACT2_LABEL': ('', 'Введите название контакта (пример: Vk, Telegram).',),
    'CONTACT2_URL': ('', 'Вставьте ссылку на контакт.',),
    'CONTACT_DESCRIPTION': (
        'Уважаемые покупатели, eсли у вас возникли какие-либо вопросы, вы всегда можете связаться с нами по контактным данным.',
        'Введите описание контактов.'),

    "SUBCATEGORY_NAME": ('Подкатегория', 'Укажите название поля для подкатегории.'),
    "PARAM1": ('Параметр1', 'Укажите нвазние для первого поля.',),
    "PARAM2": ('Параметр2', 'Укажите нвазние для второго поля.',),
    "PARAM3": ('Параметр3', 'Укажите нвазние для третьего поля.',),
    "PARAM4": ('Параметр4', 'Укажите нвазние для четвёртого поля.',),

    "YOUTUBE": (False, 'Показывать данные о канале.'),
    "YOUTUBE_LOGO": ('', 'Вставьте изображение вашего канала.', 'image_field'),
    "YOUTUBE_URL": ('', 'Ссылка на ваш канал.'),
    "YOUTUBE_TITLE": ('Магазин блогера', 'Укажите заголовок.'),
    "YOUTUBE_TEXT": ('Магазин принадлежит известному ютуберу с большой аудиторией.', 'Укажите описание.'),
}

CONSTANCE_CONFIG_FIELDSETS = {
    '1. Общие настройки.': ('SITE_NAME', 'LOGO_IMAGE', 'PANEL_TEXT', 'GIFTS', 'CHECK_PAYMENTS_TIMEOUT', 'MAINTENANCE'),
    '2. Настройки магазина. ': ('SUBCATEGORY_NAME', 'PARAM1', 'PARAM2', 'PARAM3', 'PARAM4'),
    '3. Эти настройки находятся в конце сайта. Если ключ равен -1, будет использовано настоящее значение.': (
        'USERS_COUNT', 'TODAY_USERS_COUNT', 'PURCHASES_COUNT'),
    "4. Контакты. Их можно посмотреть на странице /support/. Не обязательно.": ('CONTACT_DESCRIPTION',
                                                                                'CONTACT1', 'CONTACT1_LABEL',
                                                                                'CONTACT1_URL', 'CONTACT2',
                                                                                'CONTACT2_LABEL', 'CONTACT2_URL'),
    "5. Гарантии. Данные настройки отображаются на старнице с гарантиями": ('YOUTUBE', 'YOUTUBE_TITLE', 'YOUTUBE_TEXT',
                                                                            'YOUTUBE_URL', 'YOUTUBE_LOGO')
}

JET_SIDE_MENU_COMPACT = True

try:
    from .local_settings import *
except ImportError:
    from .prod_settings import *
